name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
    check-bats-version:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                node-version: '20'
            - run: npm install -g bats
            - run: bats -v    
    my_first_job:
        runs-on: ubuntu-latest
        steps:
            - name: My first step - check out repository
              uses: actions/checkout@v4
            - name: Use local hello-world-action
              uses: ./.github/actions/hello-world-action
              with:
                who-to-great: "GitHub Actions"
            - name: My Second step
              uses: docker://alpine:3.8